import time
import subprocess
import requests
import os
import signal
import sys
from pathlib import Path

def test_scenarios():
    # 1. Start the server
    print("Starting server...")
    # Use a log file for server output
    log_file = open("server.log", "w")
    server_process = subprocess.Popen(
        ["uvicorn", "nanobot.api.main:app", "--host", "0.0.0.0", "--port", "8001"],
        stdout=log_file,
        stderr=log_file,
        preexec_fn=os.setsid
    )
    
    # Wait for server to be ready
    time.sleep(15) 
    
    base_url = "http://localhost:8001"
    
    try:
        # Scenario 1: New user with traits
        print("\n--- Scenario 1: Creating new user with traits ---")
        user_id = "test_user_llm_1"
        
        # Create user
        resp = requests.post(f"{base_url}/users", json={"user_id": user_id})
        print(f"Create user response: {resp.status_code}")
        
        # Update watchlist
        watchlist = {
            "stocks": ["NVDA", "TSLA", "AAPL"],
            "influencers": ["Elon Musk", "Cathie Wood"],
            "keywords": ["AI", "EV", "Semiconductors"]
        }
        resp = requests.put(f"{base_url}/users/{user_id}/watchlist", json=watchlist)
        print(f"Update watchlist response: {resp.status_code}")
        
        # Update preferences (persona info goes into custom_data or we can just use defaults)
        # The ReportGenerator uses custom_data.persona
        preferences = {
            "language": "zh",
            "report_format": "markdown"
        }
        requests.put(f"{base_url}/users/{user_id}/preferences", json=preferences)
        
        # Scenario 2: Trigger immediate report for test_user_llm_1
        print("\n--- Scenario 2: Triggering immediate report for test_user_llm_1 ---")
        headers = {"Authorization": f"Bearer {user_id}"}
        resp = requests.post(f"{base_url}/reports", json={"report_type": "daily"}, headers=headers)
        print(f"Trigger report response: {resp.status_code}")
        
        # Scenario 3: Multiple users
        print("\n--- Scenario 3: Multiple users report generation ---")
        user_id_2 = "test_user_llm_2"
        
        # Create second user
        requests.post(f"{base_url}/users", json={"user_id": user_id_2})
        # Update watchlist for user 2
        requests.put(f"{base_url}/users/{user_id_2}/watchlist", json={
            "stocks": ["BTC", "ETH"],
            "keywords": ["Crypto", "ETF"]
        })
        
        # Trigger reports for both
        print(f"Triggering report for {user_id}...")
        requests.post(f"{base_url}/reports", json={"report_type": "daily"}, headers={"Authorization": f"Bearer {user_id}"})
        
        print(f"Triggering report for {user_id_2}...")
        requests.post(f"{base_url}/reports", json={"report_type": "daily"}, headers={"Authorization": f"Bearer {user_id_2}"})
        
        print("\nWaiting for reports to generate (calling LLM, this takes time)...")
        # Wait in increments and check
        for i in range(12): # 12 * 10s = 120s
            time.sleep(10)
            print(f"Checking for reports... ({i+1}/12)")
            workspace_base = Path("~/.nanobot/workspaces").expanduser()
            found_all = True
            for uid in [user_id, user_id_2]:
                report_dir = workspace_base / f"user_{uid}" / "reports"
                if not report_dir.exists() or not list(report_dir.glob("*.md")):
                    found_all = False
                    break
            if found_all:
                print("All reports found!")
                break
        
        # Verify reports in workspace
        workspace_base = Path("~/.nanobot/workspaces").expanduser()
        for uid in [user_id, user_id_2]:
            # Note the "user_" prefix in the directory name!
            report_dir = workspace_base / f"user_{uid}" / "reports"
            if report_dir.exists():
                reports = list(report_dir.glob("*.md"))
                print(f"User {uid} reports found: {[r.name for r in reports]}")
                if reports:
                    latest_report = max(reports, key=os.path.getmtime)
                    content = latest_report.read_text()
                    print(f"Latest report content preview for {uid}:\n{content[:300]}...\n")
                    if "模拟报告" in content or "Placeholder report" in content:
                        print(f"WARNING: Report for {uid} seems to be a MOCK report!")
                    else:
                        print(f"SUCCESS: Report for {uid} seems to be generated by LLM.")
            else:
                print(f"ERROR: Report directory for {uid} does not exist: {report_dir}")

    except Exception as e:
        print(f"An error occurred during test: {e}")
    finally:
        print("\nShutting down server...")
        os.killpg(os.getpgid(server_process.pid), signal.SIGTERM)
        log_file.close()
        
        # Print last few lines of log
        print("\n--- Server Log Tail ---")
        with open("server.log", "r") as f:
            lines = f.readlines()
            for line in lines[-20:]:
                print(line.strip())

if __name__ == "__main__":
    test_scenarios()
